# workflows:
#   cordova-android:
#     name: Cordova Android Workflow
#     environment:
#       node: latest
#       java: latest
#     scripts:
#       - name: Install SDK and Dependencies
#         script: |
#           npm install
#           npm ci
#           curl -s "https://get.sdkman.io" | bash
#           source "$HOME/.sdkman/bin/sdkman-init.sh"
#           sdk install java 11.0.20-amzn
#           sdk install gradle 7.1.1
#       - name: Add Android Platform
#         script: |
#           cordova platform add android
#       - name: Build keystore
#         script: |
#           keytool -genkeypair -v -keystore CUSTEM.keystore -storepass @CUSTEM211 -keyalg RSA -keysize 2048 -validity 10001 -alias Dcustem -storetype PKCS12 -dname "CN=Custem, OU=Custem2, O=Custem3, L=Custem3, ST=java, C=id"
#       - name: Build Bundel .adb
#         script: |
#           cordova build android --release -- --keystore=./CUSTEM.keystore --storePassword=@CUSTEM211 --alias=Dcustem --password=@CUSTEM211 --packageType=bundle
#       - name: Build Aplication .apk
#         script: |
#           cordova build android --release -- --keystore=./CUSTEM.keystore --storePassword=@CUSTEM211 --alias=Dcustem --password=@CUSTEM211 --packageType=apk
#       - name: Compress The Aplication
#         script: |
#           echo "Compresing..."
#           mkdir uploadfile
#           cp -r platforms uploadfile
#           cp -r CUSTEM.keystore uploadfile
#           zip -r ready.zip uploadfile
#           echo "get ready for upload"
#       - name: Upload APK
#         script: |
#           echo "Deploying app to Codemagic..."
#           curl -v -X POST \
#             -F "file=/Users/builder/clone/ready.zip" \
#             -H "x-auth-token: $CM_API_TOKEN" \
#             -H "content-type: multipart/form-data" \
#             https://api.codemagic.io/artifacts/upload
#     artifacts:
#       - /Users/builder/clone/ready.zip
#     publishing:
#       email:
#         recipients:
#           - ppti.jeffersontimotius@gmail.com

workflows:
  cordova-android:
    name: Cordova Android Workflow
    environment:
      node: latest
      java: latest
    scripts:
      - name: Install SDK and Dependencies
        script: |
          echo "Installing Node.js dependencies..."
          npm install
          npm ci
          echo "Installing SDKMAN..."
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          echo "Installing required Java and Gradle versions..."
          sdk install java 11.0.20-amzn
          sdk install gradle 7.1.1

      - name: Add Android Platform
        script: |
          echo "Adding Android platform to Cordova..."
          cordova platform add android

      - name: Build Keystore
        script: |
          echo "Creating Keystore..."
          keytool -genkeypair -v -keystore CUSTEM.keystore -storepass "@CUSTEM211" -keyalg RSA -keysize 2048 -validity 10001 \
            -alias Dcustem -storetype PKCS12 \
            -dname "CN=Custem, OU=Custem2, O=Custem3, L=Custem3, ST=java, C=id"

      - name: Build Bundle (.aab)
        script: |
          echo "Building Android App Bundle..."
          cordova build android --release -- \
            --keystore=./CUSTEM.keystore \
            --storePassword=@CUSTEM211 \
            --alias=Dcustem \
            --password=@CUSTEM211 \
            --packageType=bundle

      - name: Build APK (.apk)
        script: |
          echo "Building APK..."
          cordova build android --release -- \
            --keystore=./CUSTEM.keystore \
            --storePassword=@CUSTEM211 \
            --alias=Dcustem \
            --password=@CUSTEM211 \
            --packageType=apk

      - name: Compress Application Files
        script: |
          echo "Compressing application files for upload..."
          mkdir -p uploadfile
          cp -r platforms uploadfile
          cp CUSTEM.keystore uploadfile
          zip -r ready.zip uploadfile
          echo "Application files compressed into ready.zip"

      - name: Upload APK to Codemagic
        script: |
          echo "Uploading application to Codemagic..."
          curl -v -X POST \
            -F "file=@ready.zip" \
            -H "x-auth-token: $CM_API_TOKEN" \
            -H "content-type: multipart/form-data" \
            https://api.codemagic.io/artifacts/upload

    artifacts:
      - /Users/builder/clone/ready.zip

    publishing:
      email:
        recipients:
          - ppti.jeffersontimotius@gmail.com
