# workflows:
#   cordova-android:
#     name: Cordova Android Workflow
#     environment:
#       node: latest
#       java: latest
#     scripts:
#       - name: Install SDK and Dependencies
#         script: |
#           npm install
#           npm ci
#           curl -s "https://get.sdkman.io" | bash
#           source "$HOME/.sdkman/bin/sdkman-init.sh"
#           sdk install java 11.0.20-amzn
#           sdk install gradle 7.1.1
#       - name: Add Android Platform
#         script: |
#           cordova platform add android
#       - name: Build keystore
#         script: |
#           keytool -genkeypair -v -keystore CUSTEM.keystore -storepass @CUSTEM211 -keyalg RSA -keysize 2048 -validity 10001 -alias Dcustem -storetype PKCS12 -dname "CN=Custem, OU=Custem2, O=Custem3, L=Custem3, ST=java, C=id"
#       - name: Build Bundel .adb
#         script: |
#           cordova build android --release -- --keystore=./CUSTEM.keystore --storePassword=@CUSTEM211 --alias=Dcustem --password=@CUSTEM211 --packageType=bundle
#       - name: Build Aplication .apk
#         script: |
#           cordova build android --release -- --keystore=./CUSTEM.keystore --storePassword=@CUSTEM211 --alias=Dcustem --password=@CUSTEM211 --packageType=apk
#       - name: Compress The Aplication
#         script: |
#           echo "Compresing..."
#           mkdir uploadfile
#           cp -r platforms uploadfile
#           cp -r CUSTEM.keystore uploadfile
#           zip -r ready.zip uploadfile
#           echo "get ready for upload"
#       - name: Upload APK
#         script: |
#           echo "Deploying app to Codemagic..."
#           curl -v -X POST \
#             -F "file=/Users/builder/clone/ready.zip" \
#             -H "x-auth-token: $CM_API_TOKEN" \
#             -H "content-type: multipart/form-data" \
#             https://api.codemagic.io/artifacts/upload
#     artifacts:
#       - /Users/builder/clone/ready.zip
#     publishing:
#       email:
#         recipients:
#           - ppti.jeffersontimotius@gmail.com
workflows:
  android:
    name: Build Cordova Android App
    instance_type: macos-latest  # Or choose the appropriate instance type
    platform: android
    android:
      gradle:
        version: 7.0  # You can set the version you are using
    triggers:
      - schedule:
          cron: "0 0 * * *"  # Set a cron schedule if needed (daily here)
    environment:
      vars:
        APP_NAME: "MyCordovaApp"
        ANDROID_HOME: "/opt/android-sdk-linux"  # Path to Android SDK
    pre_build:
      steps:
        - script: |
            # Install Node.js dependencies
            npm install
            # Install Cordova if not already installed
            npm install -g cordova
        - script: |
            # Make sure Android SDK is installed and available
            yes | sdkmanager --licenses
            sdkmanager "platforms;android-30"  # Choose the appropriate Android platform version
            sdkmanager "build-tools;30.0.3"  # Or any other required build-tools version
    build:
      steps:
        - script: |
            # Build the Cordova app for Android
            cordova build android --release -- --keystore=my-release-key.keystore --storePassword=myPassword --alias=myAlias --password=myKeyPassword
    post_build:
      steps:
        - upload:
            artifact_path: platforms/android/app/build/outputs/apk/release/app-release.apk
            target: "Build/Android APK"
        - script: |
            # Clean up
            cordova clean
