# workflows:
#   cordova-android:
#     name: Cordova Android Workflow
#     environment:
#       node: latest
#       java: latest
#     scripts:
#       - name: Install SDK and Dependencies
#         script: |
#           npm install
#           npm ci
#           curl -s "https://get.sdkman.io" | bash
#           source "$HOME/.sdkman/bin/sdkman-init.sh"
#           sdk install java 11.0.20-amzn
#           sdk install gradle 7.1.1
#       - name: Add Android Platform
#         script: |
#           cordova platform add android
#       - name: Build keystore
#         script: |
#           keytool -genkeypair -v -keystore CUSTEM.keystore -storepass @CUSTEM211 -keyalg RSA -keysize 2048 -validity 10001 -alias Dcustem -storetype PKCS12 -dname "CN=Custem, OU=Custem2, O=Custem3, L=Custem3, ST=java, C=id"
#       - name: Build Bundel .adb
#         script: |
#           cordova build android --release -- --keystore=./CUSTEM.keystore --storePassword=@CUSTEM211 --alias=Dcustem --password=@CUSTEM211 --packageType=bundle
#       - name: Build Aplication .apk
#         script: |
#           cordova build android --release -- --keystore=./CUSTEM.keystore --storePassword=@CUSTEM211 --alias=Dcustem --password=@CUSTEM211 --packageType=apk
#       - name: Compress The Aplication
#         script: |
#           echo "Compresing..."
#           mkdir uploadfile
#           cp -r platforms uploadfile
#           cp -r CUSTEM.keystore uploadfile
#           zip -r ready.zip uploadfile
#           echo "get ready for upload"
#       - name: Upload APK
#         script: |
#           echo "Deploying app to Codemagic..."
#           curl -v -X POST \
#             -F "file=/Users/builder/clone/ready.zip" \
#             -H "x-auth-token: $CM_API_TOKEN" \
#             -H "content-type: multipart/form-data" \
#             https://api.codemagic.io/artifacts/upload
#     artifacts:
#       - /Users/builder/clone/ready.zip
#     publishing:
#       email:
#         recipients:
#           - ppti.jeffersontimotius@gmail.com

# codemagic.yml
workflows:
  build_android:
    name: Build Cordova Android App
    environment:
      vars:
        CORDOVA_ANDROID_VERSION: "12.0.0" # Adjust to your Cordova Android version
      node: latest # Use the latest version of Node.js
    scripts:
      # Install Cordova
      - name: Install Cordova
        script: npm install -g cordova
      
      # Install dependencies
      - name: Install dependencies
        script: npm ci

      # Build the Cordova Android app
      - name: Build Cordova Android App
        script: |
          cordova platform add android@$CORDOVA_ANDROID_VERSION
          cordova build android --release
      
      # Create the signed APK (if keystore is configured)
      - name: Sign APK
        script: |
          # Update these variables with your keystore information
          export KEYSTORE_PATH="path/to/your/keystore.jks"
          export KEY_ALIAS="your-key-alias"
          export STORE_PASSWORD="your-keystore-password"
          export KEY_PASSWORD="your-key-password"
          
          # Sign the APK
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore $KEYSTORE_PATH \
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk $KEY_ALIAS

          # Optimize the APK
          zipalign -v 4 \
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
            platforms/android/app/build/outputs/apk/release/app-release-signed.apk

      # Upload the APK as an artifact
      - name: Upload APK as an artifact
        script: |
          cp platforms/android/app/build/outputs/apk/release/app-release-signed.apk $CM_BUILD_DIR/app-release.apk

    artifacts:
      - $CM_BUILD_DIR/app-release.apk

    publishing:
      email:
        recipients:
          - ppti.jeffersontimotius@gmail.com
        body: |
          Hi Jefferson,

          Your Cordova Android app has been built successfully. Please find the APK attached.

          Best regards,
          Codemagic
        subject: Cordova Android App Build Success
        attachment_paths:
          - $CM_BUILD_DIR/app-release.apk
